versions.tf

I'm still seeing this when using Terraform 13
```
Error: Failed to install providers
Could not find required providers, but found possible alternatives:
hashicorp/lacework -> lacework/lacework
If these suggestions look correct, upgrade your configuration with the
following command:
The following remote modules must also be upgraded for Terraform 0.13
compatibility:
- module.config at lacework/config/aws
```
This should fix the problem but we need to validate functionality for Terraform 12.
Signed-off-by: Salim Afiune Maya <afiune@lacework.net>

fix: pin lacework provider to the registry

---

README.md
main.tf

***Issue***: https://lacework.atlassian.net/browse/ALLY-763
***Description:***
In order for resource management v2 to successfully crawl resources we will need the `s3:GetBucketPublicAccessBlock` capability.  This is achieved easily by adding the capability to Lacework's Security Audit policy.
***Additional Info:***
When merging the git commit should reference JIRA ticket ALLY-763

feat: add get-public-access-block capability

---

versions.tf

***Issue***:  N/A
***Description:***
The PR https://github.com/lacework/terraform-aws-config/pull/30 introduced a new argument `tags`
in the resource `aws_iam_policy` that was introduced in the `aws` provider version [v3.35.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.35.0)
with https://github.com/hashicorp/terraform-provider-aws/pull/18276 and therefore we need to bump
the minimum version so that users don't experience this error:
```
Error: Unsupported argument
on .terraform/modules/aws_config/main.tf line 45, in resource "aws_iam_policy" "lacework_audit_policy":
45:   tags        = var.tags
An argument named "tags" is not expected here.
```
***Additional Info:***
Reported by internal teams.

fix: bump aws provider min version to 3.35

---

examples/multiple-accounts/README.md
examples/multiple-accounts/main.tf
examples/multiple-accounts/providers.tf

Signed-off-by: Salim Afiune Maya <afiune@lacework.net>
The motivation of this PR is to have a clear example of how to configure multiple AWS accounts into multiple Lacework sub-accounts for cloud resource configuration assessment.
N/A this is an example that won't run our CI.
https://lacework.atlassian.net/browse/ALLY-1005

docs: add example to configure multiple accounts

---

README.md
main.tf
variables.tf

This PR adds a new `use_existing_iam_role_policy` variable which allows the user to provide us with a completely configured IAM role and associated policy - where we don't create/attach a policy to the provided IAM role.
This is necessary where IAM change control goes through a different process than infrastructure provisioning.
Changes mirror those made in a similar PR for the terraform-aws-cloudtrail module here: https://github.com/lacework/terraform-aws-cloudtrail/pull/93
Tested changes with existing integration and it produced the following plan:
```
Terraform will perform the following actions:
resource "aws_iam_policy" "lacework_audit_policy" {
id          = "arn:aws:iam::975442149240:policy/lwaudit-policy-e036a4f7"
name        = "lwaudit-policy-e036a4f7"
tags        = {}
}
resource …
```

feat: parameterize IAM policy attachment

---

README.md
main.tf

EFS permissions that are not part of the `SecurityAudit` policy.
Local testing.  Policy documented created with EFS permissions.
https://lacework.atlassian.net/browse/GROW-1300

feat: EFS audit policy permissions

---

README.md
main.tf

Support  EMR datasources by adding permissions to audit policy:
- elasticmapreduce:ListBootstrapActions
- elasticmapreduce:ListInstanceFleets
- elasticmapreduce:ListInstanceGroups
https://lacework.atlassian.net/browse/GROW-1364

feat: EMR permissions

---

README.md
main.tf

This adds a new statement to the Cross-Account role policy to allow ReadOnly access to AWS IdentityStore.
CI + Policy review.
RAIN-47731

feat: Add ReadOnly access to IdentityStore APIs

---

README.md
main.tf

This adds additional read-only APIs for the SSO AWS service, which are missing from the built-in AWS SecurityAudit role.
Use an existing module, update the source to be the commit ref, apply, validate the policy contains the added actions.
RAIN-63235

feat: Add ReadOnly access to SSO APIs

---

README.md
main.tf

Add Apigatewayv2 permissions for read operations that are called during RM collections.
This is a followup for https://github.com/lacework/terraform-aws-config/pull/70
- unit tests
- testing in dev8
https://lacework.atlassian.net/browse/RAIN-65489

feat: Add Apigatewayv2 related permissions

---

CHANGELOG.md

We had to do two ad-hoc releases
* https://github.com/lacework/terraform-aws-config/releases/tag/v0.5.1
* https://github.com/lacework/terraform-aws-config/releases/tag/v0.7.2
This change is syncing the CHANGELOG to include these versions.

chore: update CHANGELOG with ad-hoc releases

---

README.md
main.tf
versions.tf

I have an M1 Mac, and when I try to `init` my configuration that calls on this module (the latest stable, version 0.13.0), I get the error message
```
╷
│ Error: Required plugins are not installed
│ 
│ The installed provider plugins are not consistent with the packages
│ selected in the dependency lock file:
│   - registry.terraform.io/hashicorp/time: there is no package for registry.terraform.io/hashicorp/time 0.6.0 cached in .terraform/providers
│ 
```
This is because the `time` provider version 0.6.0 does not have a binary for my platform (`darwin_arm64`). The version 0.7.x does: https://github.com/hashicorp/terraform-provider-time/releases
**Also note:** I ran `terraform fmt` in the root directory, and that change is reflected in a `chore` commit in this branch.
I ran `terraform init` …

chore: update `time` provider to `~> 0.7`

---

README.md
main.tf

In https://lacework.atlassian.net/browse/RAIN-46948, ListBuilds and BatchGetBuilds are required. 
But we don't have permission for these two APIs. 
1. Without this change, do crawling in dev8, then, I got below error with the query.
```
select distinct status
from config_preview_status_t where service='codebuild' and request_guid ='df77bf47-b2fe-483e-a9bb-e6d2553cd00c'
```
2. With this change, do crawling in dev8, the error is gone.
Query is below
```
select distinct status
from config_preview_status_t where service='codebuild' and request_guid ='df77bf47-b2fe-483e-a9bb-e6d2553cd00c'
```
The result is:

feat(RAIN-80724): Add permissions for ListBuilds and BatchGetBuilds

---

README.md
main.tf

Based on https://lacework.atlassian.net/browse/RAIN-71778, We need to add resource coverage for aws glue ListWorkflows and BatchGetWorkflows. 
This is one of the citi requirements
Without this PR, crawl in dev8, we see the error like below.
```
An error occurred (AccessDeniedException) when calling the ListWorkflows operation (reached max retries: 0): User: arn:aws:sts::647104928493:assumed-role/lw-iam-472ef824/LACEWORK-CFG-external is not authorized to perform: glue:ListWorkflows because no identity-based policy allows the glue:ListWorkflows action", service="glue", method_name="list_workflows"
```
With this PR and also terraform apply, the error is gone

feat(RAIN-90851): Add permission for two glue APIs

---

README.md
main.tf

AWS securityaudit policy doesn't have permission for these five waf APIs, we need these APIs in link ticket https://lacework.atlassian.net/browse/RAIN-90597
Without this PR and the terraform apply, we see errors like
```
17:04:46.545 dev8.k8s.local aws-cfg-collector-shard-default 2023-11-10 01:04:46.545 +0000  ERROR    [pid: 23238] [ThreadPoolExecutor-1_0] pyservicecrawler.crawlers - envGuid="DEV8_B895FFBB65A0D5A2E543F62A2CB3CD9343293637C75D5C9BA80", startTime="1699585380000", assignmentSerial="00000475-of-00001853", msg="Exceptions were seen when fetching page with the message:", error_msg="An error occurred (AccessDeniedException) when calling the ListRules operation (reached max retries: 0): User: arn:aws:sts::631664038012:assumed-role/madroxqan-laceworkcwssarole/LACEWORK-CFG-external …
```

feat(RAIN-90870): Add permission for five waf-regional APIs

---

README.md
main.tf

We are missing permission for tags call
Trigger collection in dev8, and verify that the tag shows up. 
Verified with the follwoing query.
```
use schema AWS_CFG_INTERNAL;
select distinct resource_tags from aws_cfg_internal.config_details_t where service ='glacier' 
and PROPS:isSummaryRow = false 
```
https://lacework.atlassian.net/browse/RAIN-91113

feat(RAIN-91113): Add glacier permission for tags call

---

README.md
main.tf

Jira ticket is here 
https://lacework.atlassian.net/browse/RAIN-91423
aws SecurityAudit policy doesn't have permission for these three SNS APIs. 
In this PR, I am adding permissions for these three APIs.
The detail test is here https://docs.google.com/document/d/19HrNdVyQrCXARHzPYvOkq4Y3DZvJRmIC3GxKjDU7Np4/edit
1. Without the terraform change, we see all  Access Denied error. 
2. I changed terraform module for a test user. 
We no longer see access denied error for the user
https://lacework.atlassian.net/browse/RAIN-91423

feat(RAIN-91423): Add permissions for three sns APIs

---

README.md
main.tf

We do not have permission for get-api-keys in apigateway and apigatewayv2. 
In this PR, we are adding permissions for this API. 
First of all, apigateway and apigatewayv2 are controlled by the same iam actions.
In securityAudit, it actually has permissions for get APi for apigateway and apigatewayv2, but not for resource get-api-keys
Verified that the error is access denied without the change. 
With this PR on the terraform change, access denied is gone.
Detail test is here https://docs.google.com/document/d/1eQowgxHJ6JXQdMx3oMI5usrI-TvqXq6iw3sm9AqsJp0/edit
https://lacework.atlassian.net/browse/RAIN-91433

feat(RAIN-91433): Add permission for get-api-keys in apigateway and apigatewayv2

---

README.md
output.tf

Add integration ID for external reference.
Manual execution.
https://lacework.atlassian.net/browse/GROW-2876

feat(GROW-2876): add output for lacework integration ID

---

main.tf

We are missing permissions for three apigateway resources: sdk-types, base-path-mapping, usage-plans
1. Add resources in our dev8 environment.
2. Trigger the collection without the change. 
3. Check the log and I do see access denied errors https://onenr.io/01wZr1a64w6
4. Run terraform apply to our test account.
5. Trigger the collection again (The new collection started around 11am pdt on Oct 3)
Verify that no errors on access denied
https://onenr.io/0VjYrlO9vQ0

fix(RAIN-93896): Add permisssions for three ApiGateway resources

---

main.tf

Add permission in StepFunctions
Tested locally with `terraform apply`
[LINK-3087
](https://lacework.atlassian.net/browse/LINK-3087)

fix(LINK-3087): Add permission in StepFunctions

---

README.md
main.tf

Adding permission for AWS role so that service coverage for SESv2 can successfully retrieve needed information.
Tested in Tilt for enabled APIs that were failing due to access denied before applying this terraform.
https://lacework.atlassian.net/browse/RAIN-71255

feat(RAIN-71255): Add AWS permission for sesv2 APIS

---

main.tf

The discussion is here https://lacework.slack.com/archives/CR6RN9PSL/p1732207375373039
AWS announces the following change.
Essentially, it says that BatchGetworkflows will get access denied if the rule says Getworkflow is denied. 
To be safe, we explicitly set allow for operation glue:Getworkflow.
```
We identified an issue with AWS Glue BatchGet APIs that requires your action. Currently, Glue BatchGet* APIs run successfully despite a Deny condition on one or more of the underlying Get operations. On December 16, 2024, we will deploy a fix for this to ensure BatchGet* APIs will fail with an AccessDeniedException if there is a Deny condition on one of the corresponding Get* operations. Your account has policies which include these contradicting statements. Please refer to the 'Affected …
```

feat(LINK-3437): Add permission for Glue:Getworkflow

---

README.md
main.tf

Missing couple API permissions of new added AWS service Cognito-idp
Tested in Dev8
- Before
- After
[RAIN-94095](https://lacework.atlassian.net/browse/RAIN-94095)
[RAIN-94095]: https://lacework.atlassian.net/browse/RAIN-94095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat(RAIN-94095): add permission for AWS Cognito-idp service

---

README.md
main.tf

Add terraform permissions for AWS service compute-optimizer
Tested in tilt. Permissions are added only for `dev8-rm-test` account (249446771485). By running the queries below, we can see AccessDeniedException in other accounts except account_id of 249446771485.
```
-- Collection completed for envGuid: DEV8_B895FFBB65A0D5A2E543F62A2CB3CD9343293637C75D5C9BA80 
-- with startTime: 2024-12-04T08:10:00 and endTime: 2024-12-04T08:20:00
use database DEV8_CDB_DEV8_B895FFBB65A0D5A2E543F62A2CB3CD9343293637C75D5C9BA80;
select request_guid, start_time, end_time from aws_cfg_internal.config_summary_t
where start_time = '2024-12-04T08:10:00-00:00' and end_time = '2024-12-04T08:20:00-00:00';
SELECT DISTINCT account_id, service, api_key, status
FROM aws_cfg_internal.config_preview_details_t
WHERE …
```

RAIN-94027: add permission for compute-optimizer

---

main.tf

`[Glue:GetWorkflow](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-workflow.html#aws-glue-api-workflow-GetWorkflow)` instead of GetWorkflows
[LINK-3464](https://lacework.atlassian.net/browse/LINK-3464)
[LINK-3464]: https://lacework.atlassian.net/browse/LINK-3464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fix the GetWorkflow typo

---

README.md
main.tf

Adding permissions for APIs under service AMP(APS) Managed Service for Prometheus
Initially no permission for all APIs under APS, tested this in tilt and confirms that.
Added the permission through terraform and can confirm that all implicit access permission denied errors are gone.
[AMP test logs without permission](https://drive.google.com/file/d/1snEK-TGP_RnW1QBk3t9Jt6NfyRKgm7K5/view?usp=drive_link)
[AMP test logs with permission](https://drive.google.com/file/d/103qCQRAhTOMLRZqEnmabxI2vtZmchDBx/view?usp=drive_link)
https://lacework.atlassian.net/browse/RAIN-94144

feat(RAIN-94144): Add permission for service AMP

---

README.md
main.tf

Add missing permissions for AWS appstream service
Tested in Dev8
- Before
- After
[RAIN-94160](https://lacework.atlassian.net/browse/RAIN-94160)
[RAIN-94160]: https://lacework.atlassian.net/browse/RAIN-94160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat(RAIN-94160): Add permissions for AWS appstream service

---

README.md
main.tf

Add permissions for AWS Personalize service
Tested in tilt
- Before
- After
[RAIN-94178](https://lacework.atlassian.net/browse/RAIN-94178)
[RAIN-94178]: https://lacework.atlassian.net/browse/RAIN-94178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat(RAIN-94178): Add AWS Personalize service permissions

---

main.tf

Removing permissions that already exist
Tested in DEV account

chore(): Remove permission that already exist in v48 security audit policy

---

README.md
main.tf

AWS iam policy can only have up to 6144 chars. We need another policy to maintain the new services' permissions.
Modified terraform to have 2 policies created and attach to the same role.
Added permission for FIS, codeartifact.
Added tag call permission for SES, backup and AMP
Adding permission for compute-optimizer, and kinesisvideos
Tested in DEV integration.
https://docs.google.com/document/d/1rkfXAQUaA32_IShki6mTmf2aZF4HRiMSGX6_-I4pf8w/edit?userstoinvite=ljohnny@fortinet.com&sharingaction=manageaccess&role=writer&tab=t.0
https://lacework.atlassian.net/browse/RAIN-94239

feat(RAIN-94239): Rm modify terraform to add a policy

---

README.md
main.tf

Adding readonly permissions for services:
memoryDB
qbusiness
qconnect
qapps
resourcegroups
servicecatalogappregistry
oam
clouddirectory
optimizationhub
budgets
billingconsole
Applied to dev aws account and tested the permission in the iam policy simulator
https://lacework.atlassian.net/browse/RAIN-94335

feat(RAIN-94335): Adding permission for terraform version 0.19.0

---

main.tf

Some permission in our custom policy are overlapping with security audit policy, we need to remove the redundant ones to free up space.
Tested in our dev env and ran.
https://lacework.atlassian.net/browse/RAIN-94454

chore(RAIN-94454): Remove two redundant policies

---

README.md
main.tf

Adding permissions for upcoming services including:
1. Free Tier
2. ACM-PCA
3. Lambda(partial)
4. Schemas(partial)
5. Scheduler
6. Lakeformation
7. DynamoDB(Partial)
8. Appconfig
9. AppFlow
10. EBS
11. DATASYNC
Testing in DEV account
https://docs.google.com/document/d/1raSa62A7Q1sqbdYhxU2z73OrMVjS7odE995yfnN6NKI/edit?tab=t.0
https://lacework.atlassian.net/browse/RAIN-94565

feat(RAIN-94565): Added 11 services for TF permissions 20.0.0
